from .early_stopping import EarlyStopping
from .update_strategies import classical_consequents_estimation_with_OLS, premises_update_with_gradient_descent
from .training_algorithms import Hybrid_learning_algorithm