from .early_stopping import EarlyStopping
from .update_strategies import optimizer_training_epoch, classical_consequents_estimation_with_OLS
from .training_algorithms import Hybrid_learning_algorithm, Optimizer_training, base_model_trainer
from .sonfis import SONFIS, alt_SONFIS