import torch

def gaussian2(x, p):
    '''
    It is used as a membership function and calculates gaussian values based on the input data and premise parameters
    of the ANFIS model (membership degrees). Emulates the following gaussian function:
    
    .. image:: _build/html/_static/gauss2.png
        :width: 260
        :align: center
    
    :param x: Tensor of input data.
    :type x: torch.tensor
    
    :param p: 3D parameter tensor containing 'mu' and 'sigma' parameters by data dimension and by ANFIS rule.
    :type p: torch.tensor
    
    :return: Tensor with resulting gaussian values.
    :rtype: torch.tensor

    **Explanation:**
    This function calculates gaussian values based on the input data `x` and the parameters `p`.
    It ensures that the standard deviation values in `p` are not zero by replacing them with a small
    value (1e-6). The formula used to compute the gaussian values is:

    .. image:: _build/html/_static/gaussian2.png
        :width: 350
        :align: center

    .. note::
    
        - If `p[:, :, 1]` is zero, it is replaced with 1e-6 to prevent division by zero.
        - The premise parameters of the ANFIS model are autogenerated, but it is important to keep in mind that, considering that the input data has N dimentions and there are K rules on the model, its structure is as follows:
        
        .. image:: _build/html/_static/p2.png
            :width: 320
            :align: center
        
    '''
    return torch.exp(-0.5 * torch.pow((x - p[:, :, 0])/torch.where(p[:, :, 1] == 0, torch.tensor(1e-6), p[:, :, 1]), 2))



def gaussian3(x, p):
    '''
    It is used as a membership function and calculates gaussian values based on the input data and premise parameters
    of the ANFIS model (membership degrees). Emulates the following gaussian function:
    
    .. image:: _build/html/_static/gauss3.png
        :width: 320
        :align: center
    
    :param x: Tensor of input data.
    :type x: torch.tensor
    
    :param p: 3D parameter tensor containing 'mu', 'sigma' and 'f' (as scalar) parameters by data dimension and by ANFIS rule.
    :type p: torch.tensor
    
    :return: Tensor with resulting gaussian values.
    :rtype: torch.tensor

    **Explanation:**
    This function calculates gaussian values based on the input data `x` and the parameters `p`.
    It ensures that the standard deviation values in `p` are not zero by replacing them with a small
    value (1e-6). The formula used to compute the gaussian values is:
    
    .. image:: _build/html/_static/gaussian3.png
        :width: 480
        :align: center

    .. note::
        - If `p[:, :, 1]` is zero, it is replaced with 1e-6 to prevent division by zero.
        - The premise parameters of the ANFIS model are autogenerated, but it is important to keep in mind that, considering that the input data has N dimentions and there are K rules on the model, its structure is as follows:
        
        .. image:: _build/html/_static/p3.png
            :width: 320
            :align: center
        
    .. warning::
    
        - The model functions and algorithms are not designed to support this membership function, they are all designed to work with the gaussian2.

    '''
    return p[:, :, 2] * torch.exp(-torch.pow((x - p[:, :, 0])/torch.where(p[:, :, 1] == 0, torch.tensor(1e-6), p[:, :, 1]), 2))



def weighted_linear(x, c, w):
    """
    Compute the weighted linear combination of input features and coefficients (representing the
    consequent parameters of the ANFIS model). Its used to calculate the individual outputs 'f k' of each rule 'k' of
    the ANFIS model. Emulates the following calculation for all the rules:
    
    .. image:: _build/html/_static/linear.png
        :width: 480
        :align: center
        
    Where 'c i,k' is the ith consequent parameter of the k-th ANFIS rule, 'x j' is the jth dimention of the input data 'x'
    and 'w k' is the normalized firing level of kth rule asociated to the input 'x' obtained in previous layers of the model.
    This operation is applied to each of the ANFIS rules simultaneously.

    :param x: Tensor of input data.
    :type x: torch.tensor
    
    :param c: Coefficients tensor for the linear combination (consequent parameters).
    :type c: torch.tensor
    
    :param w: Weights tensor for element-wise multiplication.
    :type w: torch.tensor

    :return: Resulting weighted linear combination.
    :rtype: torch.tensor

    **Explanation:**
    This function calculates the weighted linear combination of the input features `x` and the coefficients `c`.
    It involves matrix multiplication of the input features by the transposed coefficients (excluding the last column),
    adding the last column of coefficients, and then element-wise multiplication by the weights `w`. The formula used to 
    compute this function is:
    
    .. image:: _build/html/_static/weighted_linear.png
        :width: 520
        :align: center

    .. note::
        - The weights `w` are applied element-wise.
        - The consequent parameters of the ANFIS model are autogenerated, but it is important to keep in mind that, considering that the input data has N dimentions and there are K rules on the model, its structure is as follows:
        
        .. image:: _build/html/_static/c.png
            :width: 320
            :align: center
    
    """
    return (x @ c[:, :-1].t() + c[:, -1]).mul(w)




